config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'
  

  get 'auth/:provider/callback', to: 'admin/sessions#oauth'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'admin/sessions#destroy', as: 'signout'

  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index' 
  get 'posts/report'

  get 'users/created' => 'users#created', as: 'created'


  namespace :admin do
    get 'login' => 'sessions#new', as: 'login'
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/update'
    get 'users/edit'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories
  resources :users

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true

    def self.search(query)
        where("name like ?", "%#{query}%")
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    has_rich_text :body

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image, :default_url => "rails1.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def self.search(query)
        where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
    end

    def as_json(options={})
      { :title => title }  # Only including title for the API
    end
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    #validates :password, presence: true
    #validates :password, confirmation: true 


    #BCrypt authentication
    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user 
        else
            nil
        end
    end

    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end
    
    #Omniauth authentication
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
    end

    def self.create_from_omniauth(auth)
        create! do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.name = auth["info"]["name"]
            user.email = auth["info"]["email"]
        end
    end

    #Serach function
    def self.search(query)
        where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private
        def current_user
            @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end

    def verify_logged_in
        unless current_user
            redirect_to admin_login_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :verify_logged_in, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment added'

    redirect_to post_path(@post)
  end

  def destroy

    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
    @categories = Category.all


    respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @posts }
        format.json { render :json => @posts }
      end
  end

  def report
    @categories = Category.all
    ReportWorker.perform_async("27-10-2020", "28-10-2020")
    
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @page_title = 'Add user'
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            EmailSenderJob.perform_later(@user)
            render 'created'
        else 
            render 'new'
        end
    end

    def created
    end

     private
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background-image: url("<%= asset_path('background')%>");
        background-size: 100%;
        background-repeat: no-repeat;
        }
    </style>

  </head>
  <body>
    <nav class="navbar navbar-expand-md">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path%>">
          <h1>rBlog</h1>
          <span>/Manager</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= params[:controller] == 'admin/posts' ? 'active' : ''%>">
              <a class="nav-link" href="<%= admin_posts_path%>">Posts</a>
            </li>
            <li class="nav-item <%= params[:controller] == 'admin/categories' ? 'active' : ''%>">
              <a class="nav-link" href="<%= admin_categories_path%>">Categories</a>
            </li>
            <li class="nav-item <%= params[:controller] == 'admin/users' ? 'active' : ''%>">
              <a class="nav-link" href="<%= admin_users_path%>">Users</a>
            </li>
          </ul>
          <!-- default form for search
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Submit</button>
          </form>-->

          <%= render 'partials/admin/search'%>
          
        </div>
      </div>
    </nav>

    

    <section>
    


      <div class="container">
        <div class="row">
          <div class="col-md-12"> 


          </div>
        </div>
        <div class="row">
          <div class="col-md-12"> 
            <br>
            <div class="<%= params[:action] == 'new' || params[:action] == 'edit' || params[:action] == 'show'? 'card card-new shadow' : 'card card-body bg-light'%>">
                <% if flash[:notice]%>
                  <div class="alert alert-success"><%= flash[:notice]%></div>
                <%end%>

                <% if flash[:alert]%>
                  <div class="alert alert-danger"><%= flash[:alert]%></div>
                <%end%>

                <%= yield %>
            </div>
          </div>
        </div>
      </div>

    </section>
      
    <div class="container">
      <%= render 'partials/admin/footer'%>
    </div>
    
    
    <script type= "text/javascript">
      textarea = document.querySelector("textarea"); 
      textarea.addEventListener('input', autoResize, false); 
  
    function autoResize() { 
        this.style.height = 'auto'; 
        this.style.height = this.scrollHeight + 'px'; 
    }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login | RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'admin/login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background-image: url("<%= asset_path('background')%>");
        background-size: 100%;
        background-repeat: no-repeat;
        }
    </style>

    </head>
    <body>
        <div class="container">
            <%= yield%>
        </div>
    </body>
</html>

app/views/partials/admin/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-4 col-md">
                <img class="mb-2" src="https://simpleicon.com/wp-content/uploads/blog.png" alt="" width="24" height="24">
                <small class="d-block mb-3 text-muted">Copyright &copy; 2020, rBlog</small>
            </div>
            <div class="col-2 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Random feature</a></li>
                    <li><a class="text-muted" href="#">Team feature</a></li>
                    <li><a class="text-muted" href="#">Stuff for developers</a></li>
                </ul>
            </div>
            <div class="col-2 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Resource</a></li>
                    <li><a class="text-muted" href="#">Resource name</a></li>
                    <li><a class="text-muted" href="#">Another resource</a></li>
                </ul>
            </div>
            <div class="col-2 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="about.html">Team</a></li>
                    <li><a class="text-muted" href="#">Locations</a></li>
                    <li><a class="text-muted" href="#">Privacy</a></li>
                </ul>
            </div>
            <div class="col-2 col-md">
                <ul class="list-unstyled text-small">
                    <li>
                        <div id="user_nav" class="float-right">
                            <% if current_user %> Logged in as <%= current_user.name %>. 
                            <br><br><%= link_to "Log out", admin_logout_path, class: "btn btn-primary" %>
                            <% else %>
                            <%= link_to "Log in", admin_login_path,  class: "btn btn-primary"%>
                            <% end %>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts'%>

    <%= form_tag(admin_posts_path, :method => "get", id: "search-form", class: "search-form float-right") do%>
        <div class="form-inline my-2 my-lg-0">
            <%= text_field_tag :search, params[:search], placeholder: "Search posts", class: "form-control mr-sm-2"%>
            <%= submit_tag "Search", :name => nil, class: "btn btn-secondary my-2 my-sm-0"%>
        </div>
    <% end %>

<% elsif params[:controller] == 'admin/categories'%>

    <%= form_tag(admin_categories_path, :method => "get", id: "search-form", class: "search-form float-right") do%>
        <div class="form-inline my-2 my-lg-0">
            <%= text_field_tag :search, params[:search], placeholder: "Search categories", class: "form-control mr-sm-2"%>
            <%= submit_tag "Search", :name => nil, class: "btn btn-secondary my-2 my-sm-0"%>
        </div>
    <% end %>

<% elsif params[:controller] == 'admin/users'%>

    <%= form_tag(admin_users_path, :method => "get", id: "search-form", class: "search-form float-right") do%>
        <div class="form-inline my-2 my-lg-0">
            <%= text_field_tag :search, params[:search], placeholder: "Search users", class: "form-control mr-sm-2"%>
            <%= submit_tag "Search", :name => nil, class: "btn btn-secondary my-2 my-sm-0"%>
        </div>
    <% end %>
    
<% end %>