config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'
  

  get 'auth/:provider/callback', to: 'admin/sessions#oauth'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'admin/sessions#destroy', as: 'signout'

  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index' 
  get 'posts/report'

  get 'users/created' => 'users#created', as: 'created'


  namespace :admin do
    get 'login' => 'sessions#new', as: 'login'
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/update'
    get 'users/edit'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories
  resources :users

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true

    def self.search(query)
        where("name like ?", "%#{query}%")
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    has_rich_text :body

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image, :default_url => "rails1.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def self.search(query)
        where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
    end

    def as_json(options={})
      { :title => title }  # Only including title for the API
    end
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    #validates :password, presence: true
    #validates :password, confirmation: true 


    #BCrypt authentication
    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user 
        else
            nil
        end
    end

    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end
    
    #Omniauth authentication
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
    end

    def self.create_from_omniauth(auth)
        create! do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.name = auth["info"]["name"]
            user.email = auth["info"]["email"]
        end
    end

    #Serach function
    def self.search(query)
        where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @page_title = 'Add category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @categories = Category.all
    if @category.save
        flash[:notice] = 'Category created'
        render 'index'
    else 
        render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @categories = Category.all
    if @category.update(category_params)
      flash[:notice] = 'Category updated'
      render 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @categories = Category.all
    @category.destroy

    flash[:alert] = 'Category removed'

    render 'index'
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @categories = Category.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private
        def current_user
            @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end

    def verify_logged_in
        unless current_user
            redirect_to admin_login_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :verify_logged_in, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment added'

    redirect_to post_path(@post)
  end

  def destroy

    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
    @categories = Category.all


    respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @posts }
        format.json { render :json => @posts }
      end
  end

  def report
    @categories = Category.all
    ReportWorker.perform_async("27-10-2020", "28-10-2020")
    
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @page_title = 'Add user'
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            EmailSenderJob.perform_later(@user)
            render 'created'
        else 
            render 'new'
        end
    end

    def created
    end

     private
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/edit.html.erb
<div class="card-body new-content">


<h2>Edit category</h2>

<%= form_for [:admin, @category] do |f|%>

	<% if @category.errors.any?%>
		<% @category.errors.full_messages.each do |msg|%>
			<div class ="alert alert-danger"><%= msg%></div>
		<%end%>
	<%end%>

    <div class="form-group">
		<%= f.text_field :name, {placeholder: 'Name', class:'form_input label'} %><br />
	</div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_categories_path, class:'btn btn-primary' %>


<% end %>

</div>

app/views/admin/categories/index.html.erb
<div class ="m-3">
<h2 class="ml-4">Manage categories <%= link_to "Create new", new_admin_category_path, class:'btn btn-success float-right mr-4'%></h2>

<br>

<table class = "table table-striped shadow-sm">
    <tr>
        <th>Category title</th>
        <th>Date created</th>
        <th>Manager controlls</th>
    </tr>

    <% @categories.each do |category|%>

    <tr>
        <td><%= category.name%></td>
        <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p')%></td>
        <td><%= link_to "Edit", edit_admin_category_path(category), class: 'btn btn-warning'%> <%= link_to "Delete", admin_category_path(category), class: 'btn btn-danger', method: :delete, 
                                            data: {confirm: 'Are you sure?'}%></td>
    </tr>

    <% end %>
</table>

<%= will_paginate @posts%>
</div>

app/views/admin/categories/new.html.erb
<div class="card-body new-content">


<h2>Add new category</h2>

<%= form_for [:admin, @category] do |f|%>

	<% if @category.errors.any?%>
		<% @category.errors.full_messages.each do |msg|%>
			<div class ="alert alert-danger"><%= msg%></div>
		<%end%>
	<%end%>




    <div class="form-group">
		<%= f.text_field :name,  {placeholder: 'Name', class:'form_input label'} %><br />
	</div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_categories_path, class:'btn btn-primary' %>


<% end %>
</div>

app/views/categories/show.html.erb
<h2 class="mb-4"style= "color: white;"><%= @category.name%></h2>

<div id="posts-index">
  <%if @posts.exists?%>
    <% @posts.each_slice(2) do |post|%>
      <div class ="row">
        <% post.each do |post|%>
          <div class ="col-md-6">

            <div class="post">
              <%= image_tag post.image.url, width: '100%'%>
              <div class="post-content">
                <h3><%= post.title%></h3>
                <small class="mb-2 text-muted">Posted by <%= post.user.name%> on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p')%></small>

                <%= truncate(strip_tags(post.body.to_s), length: 200)%>
                
                <div class="mdc-card__actions mt-2">
                  <div class="mdc-card__action-buttons">
                    <button onclick="location.href='<%= post_path(post)%>'" class="mdc-button mdc-card__action mdc-card__action--button" type="button">
                      <div class="mdc-button__ripple"></div>
                        <span class="mdc-button__label">Read</span>
                    </button>
                    <button onclick="location.href='<%= about_path%>'" class="mdc-button mdc-card__action mdc-card__action--button" type="button">
                      <div class="mdc-button__ripple"></div>
                        <span class="mdc-button__label">Bookmark</span>
                    </button>
                  </div>
                  <div class="mdc-card__action-icons">
                    <button class="material-icons mdc-icon-button mdc-card__action mdc-card__action--icon" title="Share">share</button>
                    <button class="material-icons mdc-icon-button mdc-card__action mdc-card__action--icon" title="More options">more_vert</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end%>
      </div>

      <br>
    <%end%>
  <%else%>
  <p> No posts  yet...</p>  
  <%end%>
</div>