config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'
  

  get 'auth/:provider/callback', to: 'admin/sessions#oauth'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'admin/sessions#destroy', as: 'signout'

  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index' 
  get 'posts/report'

  get 'users/created' => 'users#created', as: 'created'


  namespace :admin do
    get 'login' => 'sessions#new', as: 'login'
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/update'
    get 'users/edit'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories
  resources :users

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    has_rich_text :body

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image, :default_url => "rails1.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def self.search(query)
        where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
    end

    def as_json(options={})
      { :title => title }  # Only including title for the API
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @page_title = 'Add post'
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)

    if params[:post][:image].blank?
      @post.image = nil
    end

    if @post.save
      flash[:notice] = 'Post created'
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)

    if params[:post][:image].blank?
      @post.image = nil
    end
    if @post.update(post_params)
      flash[:notice] = 'Post updated'
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    @post.destroy

    flash[:alert] = 'Post removed'

    redirect_to admin_posts_path
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :image, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
    @categories = Category.all


    respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @posts }
        format.json { render :json => @posts }
      end
  end

  def report
    @categories = Category.all
    ReportWorker.perform_async("27-10-2020", "28-10-2020")
    
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div id="posts-index">
  <%if @posts.exists?%>
    <% @posts.each_slice(2) do |post|%>
      <div class ="row">
        <% post.each do |post|%>
          <div class ="col-md-6">

            <div class="post">
              <%= image_tag post.image.url, width: '100%'%>
              <div class="post-content">
                <h3><%= post.title%></h3>
                <small class="mb-2 text-muted">Posted by <%= post.user.name%> on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p')%></small>

                <%= truncate(strip_tags(post.body.to_s), length: 200)%>
                
                <div class="mdc-card__actions mt-2">
                  <div class="mdc-card__action-buttons">
                    <button onclick="location.href='<%= post_path(post)%>'" class="mdc-button mdc-card__action mdc-card__action--button" type="button">
                      <div class="mdc-button__ripple"></div>
                        <span class="mdc-button__label">Read</span>
                    </button>
                    <button onclick="location.href='<%= about_path%>'" class="mdc-button mdc-card__action mdc-card__action--button" type="button">
                      <div class="mdc-button__ripple"></div>
                        <span class="mdc-button__label">Bookmark</span>
                    </button>
                  </div>
                  <div class="mdc-card__action-icons">
                    <button class="material-icons mdc-icon-button mdc-card__action mdc-card__action--icon" title="Share">share</button>
                    <button class="material-icons mdc-icon-button mdc-card__action mdc-card__action--icon" title="More options">more_vert</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end%>
      </div>
      <br>
    <%end%>
  <%= link_to 'Generate a report...', posts_report_path, class: "btn btn-secondary"%>
  <%else%>
  <p style="color: white;"> No posts  yet...</p>  
  <%end%>
</div>

app/views/posts/report.html.erb
<div class="card card-body">
    <h1> GENERATING A REPORT </h1>
</div>

app/views/posts/show.html.erb
<div class="card">
    <%= image_tag @post.image.url, width: '100%', class: "card-img-top"%>
    <div class="card-body">
        <h2 class="card-title page-header"><%= @post.title%></h2>
        <h6 class="card-subtitle mb-3 text-muted"> Posted by <%= @post.user.name%> on <%= @post.created_at.to_time.strftime('%B %e at %l:%M %p')%></h6>
        <p class="card-text"><%= @post.body%></p>
    </div>
</div>

<%= render 'partials/comments'%>