config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'
  

  get 'auth/:provider/callback', to: 'admin/sessions#oauth'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'admin/sessions#destroy', as: 'signout'

  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index' 
  get 'posts/report'

  get 'users/created' => 'users#created', as: 'created'


  namespace :admin do
    get 'login' => 'sessions#new', as: 'login'
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/update'
    get 'users/edit'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories
  resources :users

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end
  
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    #validates :password, presence: true
    #validates :password, confirmation: true 


    #BCrypt authentication
    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user 
        else
            nil
        end
    end

    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end
    
    #Omniauth authentication
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
    end

    def self.create_from_omniauth(auth)
        create! do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.name = auth["info"]["name"]
            user.email = auth["info"]["email"]
        end
    end

    #Serach function
    def self.search(query)
        where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @page_title = 'Add user'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @users = User.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
    
    if @user.save
        EmailSenderJob.perform_later(@user)
        flash[:notice] = 'User created'
        render 'index'
    else 
        render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @users = User.all
    if @user.update(user_params)
      flash[:notice] = 'User updated'
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @users = User.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end

    @user.destroy

    flash[:alert] = 'User removed'

    render 'index'
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    else
      @users = User.all.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :uid, :provider)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @page_title = 'Add user'
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            EmailSenderJob.perform_later(@user)
            render 'created'
        else 
            render 'new'
        end
    end

    def created
    end

     private
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="card-body new-content">

<h2>Edit user</h2>
<%= form_for [:admin, @user] do |f|%>

	<% if @user.errors.any?%>
		<% @user.errors.full_messages.each do |msg|%>
			<div class ="alert alert-danger"><%= msg%></div>
		<%end%>
	<%end%>

    <div class="form-group">
		<%= f.text_field :name, {placeholder: 'Name', class:'form_input label'} %>
	</div>

	<div class="form-group">
		<%= f.text_field :email, {placeholder: 'Email', class:'form_input label'} %>
	</div>

	<div class="form-group">
		<%= f.password_field :password, {placeholder: 'New password', class:'form_input label'} %>
	</div>

    <div class="form-group">
		<%= f.password_field :password_confirmation, {placeholder: 'New password confirmation', class:'form_input label'}%>
	</div>

    <br>

    <div style="padding-left: 20px;">
    <%= f.submit "Submit", class:'btn btn-primary shadow' %>
	<%=link_to "Cancel", admin_posts_path, class:'btn btn-primary shadow'%>
    </div>

<% end %>

</div>

app/views/admin/users/index.html.erb
<div class ="m-3">

<h2 class=" ml-4">Users <%= link_to "Create new", new_admin_user_path, class:'btn btn-success float-right mr-4'%></h2>

<br>
<% if @users.exists? %>
    <table class = "table table-striped shadow-sm">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Date joined</th>
            <th>Manager actions</th>
        </tr>

        <% @users.each do |user|%>

        <tr>
            <td><%= user.name%></td>
            <td><%= user.email%></td>
            <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p')%></td>
            <td><%= link_to "Edit", edit_admin_user_path(user), class: 'btn btn-warning'%> <%= link_to "Delete", admin_user_path(user), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'}%></td>
        </tr>

        <% end %>
    </table>

    <%= will_paginate @posts%>
    
    <% else %>

    <p class="no-posts"> There are no users </p>
<% end %>
</div>

app/views/admin/users/new.html.erb
<div class="card-body new-content">

<h2>Add new user</h2>
<%= form_for [:admin, @user] do |f|%>

	<% if @user.errors.any?%>
		<% @user.errors.full_messages.each do |msg|%>
			<div class ="alert alert-danger"><%= msg%></div>
		<%end%>
	<%end%>

    <div class="form-group">
		<%= f.text_field :name, {placeholder: 'Name', class:'form_input label'} %>
	</div>

	<div class="form-group">
		<%= f.text_field :email, {placeholder: 'Email', class:'form_input label'} %>
	</div>

	<div class="form-group">
		<%= f.password_field :password, {placeholder: 'Password', class:'form_input label'} %>
	</div>

    <div class="form-group">
		<%= f.password_field :password_confirmation, {placeholder: 'Password confirmation', class:'form_input label'}%>
	</div>

    <br>

    <div style="padding-left: 20px;">
    <%= f.submit "Submit", class:'btn btn-primary shadow' %>
	<%=link_to "Cancel", admin_posts_path, class:'btn btn-primary shadow'%>
    </div>

<% end %>

</div>